### ISSUE TITLE
about the inference error

### ISSUE THREAD

**Issue by yihe1003** [primepake/wav2lip_288x288#5]
hi，i used your code to run the trainning without any change of model. The trainning is normal. But when i run the ingerence code, the error occurs as below. have you ever met this error? Thank you 

Model loaded
  0%|                                                                                                                                             | 0/2 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 277, in <module>
    main()
  File "inference.py", line 262, in main
    pred = model(mel_batch, img_batch)
  File "/bin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "wav2lip/HD_wav2lip/wav2lip_288x288/models/wav2lipv2.py", line 117, in forward
    x = f(x)
  File "/bin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/bin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/bin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "wav2lip/HD_wav2lip/wav2lip_288x288/models/conv2.py", line 16, in forward
    out = self.conv_block(x)
  File "/bin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/bin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/bin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/bin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (2 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size

**Comment by HaSaKiYasuooo** [comment]
Hello,I have some problems with this,Could you tell me how to resolve it?
![image](https://github.com/primepake/wav2lip_288x288/assets/87591236/0c652d45-9638-4df7-b7de-8123307eab56)

**Comment by alexhmyang** [comment]
用 python3 train_syncnet_sam.py 训练后的结果，报同样的错误，请问楼主 解决了吗
