### ISSUE TITLE
The recently updated code has some issues

### ISSUE THREAD

**Issue by shaneluik1026** [primepake/wav2lip_288x288#91]
Traceback (most recent call last):
  File "/wav2lip_288x288/train_syncnet_sam.py", line 417, in <module>
    run()
  File "/wav2lip_288x288/train_syncnet_sam.py", line 376, in run
    train_dataset = Dataset('filelists/train.txt')
  File "/wav2lip_288x288/train_syncnet_sam.py", line 73, in __init__
    self.all_videos = get_image_list(file_list)
TypeError: get_image_list() missing 1 required positional argument: 'split'

Traceback (most recent call last):
  File "/wav2lip_288x288/train_syncnet_sam.py", line 9, in <module>
    from models import SyncNet_color as SyncNet
  File "/wav2lip_288x288/models/__init__.py", line 4, in <module>
    from .wav2lipv2 import Wav2Lip, Wav2Lip_disc_qual, Wav2Lip_SAM
ImportError: cannot import name 'Wav2Lip_SAM' from 'models.wav2lipv2' (/wav2lip_288x288/models/wav2lipv2.py)

It should be hparams. py and models/__init__.py The code in py was not submitted.

**Comment by primepake** [comment]
Fixed!
