### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for SyncNet_color:

### ISSUE THREAD

**Issue by pavelxx1** [primepake/wav2lip_288x288#94]
Hi
I have an issue when try to run `hq_wav2lip_sam_train`
```
use_cuda: True
Loading syncnet from checkpoint: ./savedmodel/actor/syncnet_checkpoint_288_32_000000105_2023-12-23.pth
Load checkpoint from: ./savedmodel/actor/syncnet_checkpoint_288_32_000000105_2023-12-23.pth
Traceback (most recent call last):
  File "/workspace/hq_wav2lip_sam_train.py", line 653, in <module>
    main()
  File "/workspace/hq_wav2lip_sam_train.py", line 649, in main
    run()
  File "/workspace/hq_wav2lip_sam_train.py", line 610, in run
    load_checkpoint(args.syncnet_checkpoint_path, syncnet, None, reset_optimizer=True,
  File "/workspace/hq_wav2lip_sam_train.py", line 568, in load_checkpoint
    model.load_state_dict(new_s)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SyncNet_color:
	Unexpected key(s) in state_dict: "face_encoder.20.conv_block.0.weight", "face_encoder.20.conv_block.0.bias", "face_encoder.20.conv_block.1.weight", "face_encoder.20.conv_block.1.bias", "face_encoder.20.conv_block.1.running_mean", "face_encoder.20.conv_block.1.running_var", "face_encoder.20.conv_block.1.num_batches_tracked", "face_encoder.21.conv_block.0.weight", "face_encoder.21.conv_block.0.bias", "face_encoder.21.conv_block.1.weight", "face_encoder.21.conv_block.1.bias", "face_encoder.21.conv_block.1.running_mean", "face_encoder.21.conv_block.1.running_var", "face_encoder.21.conv_block.1.num_batches_tracked". 
```

**Comment by silkcutKs** [comment]
same problem @pavelxx1  how to resolve it, thanks

**Comment by einsqing** [comment]
same problem

**Comment by pavelxx1** [comment]
u need to change valid path for .py model in header
problems with class name 🥷

**Comment by PhilanthropistBright** [comment]
> u need to change valid path for .py model in header problems with class name 🥷

what mean?   change path with args?  --syncnet_checkpoint_path  ?
