### ISSUE TITLE
AttributeError: 'HParams' object has no attribute num_checkpoints

### ISSUE THREAD

**Issue by einsqing** [primepake/wav2lip_288x288#95]
Traceback (most recent call last):
  File ".\train_syncnet_sam.py", line 418, in <module>
    run()
  File ".\train_syncnet_sam.py", line 411, in run
    train(device, model, train_data_loader,test_data_loader, optimizer,
  File ".\train_syncnet_sam.py", line 248, in train
    save_checkpoint(model, optimizer, global_step, checkpoint_dir, global_epoch, eval_loss)
  File ".\train_syncnet_sam.py", line 329, in save_checkpoint
    num_ckpts = hparams.num_checkpoints
  File "C:\Users\heqing\Desktop\wav2lip_288x288\hparams.py", line 23, in __getattr__
    raise AttributeError("'HParams' object has no attribute %s" % key)
AttributeError: 'HParams' object has no attribute num_checkpoints

**Comment by Nyquist0** [comment]
I think you could directly add the attribute num_checkpoints in the correct place of the file hparams.py. This attribute is to limit the max number of saved ckpt files.
